[package]
name = "bolt-load"
edition = "2021"
version = "0.1.0"

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[lib]
name = "bolt_load"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
derive_builder = "0.20.2"
futures = "0.3"
url = "2.5"
bytes = "1.9"
reqwest = { version = "0.12", optional = true, features = ["stream"] }

[dev-dependencies]
