[workspace]
members = [
    'crates/bolt-load',
    "crates/bolt-load-core",
    'crates/bolt-load-adapter',
    'crates/bolt-load-tests',
    "crates/bolt-load-utils",
]
resolver = "3"

[workspace.dependencies]
futures = "0.3"
bytes = "1"
thiserror = "2"
snafu = "0.8"

async-trait = "0.1"
async-lock = "3"
blocking = "1"

tracing = "0.1"

# Dev Dependencies
anyhow = "1"
tokio = "1"
tokio-util = "0.7"
pretty_assertions = "1"
n0-tracing-test = { version = "0.3.0", features = ["pretty-log-printing"] }

[patch.crates-io]
futures-util = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-task = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-core = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-channel = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-executor = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-macro = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-sink = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures-io = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
futures = { git = "https://github.com/greenhat616/futures-rs.git", rev = "ec3ef7b6" }
