[package]
name = "bolt-load"
description = "A fast, async, multi-connection parallel download library for Rust"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version = "1.88.0"

[features]
default = ["tokio", "serde", "tracing", "progressbar", "mmap"]
http = [
    "dep:headers",
    "dep:regex",
    "dep:language-tags",
    "dep:percent-encoding",
    "dep:http",
]
# terminal progress
progressbar = ["dep:indicatif"]

# adapter group
reqwest = ["bolt-load-adapter/reqwest"]
ureq2 = ["bolt-load-adapter/ureq2"]
ureq3 = ["bolt-load-adapter/ureq3"]

serde = ["dep:serde"]

# file writer opts
mmap = ["dep:memmap2", "dep:windows-sys"]

# runtime group
tokio = ["dep:tokio"]
smol = ["dep:smol"]
compio = ["dep:compio"]

tracing = ["dep:tracing", "bolt-load-utils/tracing"]

[lib]
doctest = false
name = "bolt_load"
path = "src/lib.rs"


[dependencies]
bolt-load-core = { path = "../bolt-load-core", version = "0.1" }
bolt-load-adapter = { path = "../bolt-load-adapter", version = "0.1" }
bolt-load-utils = { path = "../bolt-load-utils", version = "0.1" }

snafu = { workspace = true }
async-trait = "0.1"
futures = { workspace = true }
futures-concurrency = "7"
pin-project-lite = "0.2"
url = "2"
bytes = "1"
enum_dispatch = "0.3"
atomic_enum = "0.3"
tempfile = "3"
smol-cancellation-token = "0.1"
derive_more = { version = "2", features = ["debug"] }
statig = { version = "0.4.1", features = ["async"] }
fs-err = "3" # for detailed io error message
bitvec = "1" # for task id generation
memmap2 = { version = "0.9", optional = true } # for better random range write for files if machine is available
backon = "1" # for retry strategy
oneshot = { version = "0.2", features = [
    "async",
    "std",
] } # for cross runtime oneshot
async-waitgroup = "0.1.3" # for cross runtime wait group
async-lock = { workspace = true } # for cross runtime async lock
ranges = "0.4" # for range set operation
async-channel = "2" # for async channel
async-ringbuf = "0.3" # for spsc ring buffer channel
async-broadcast = { version = "0.7" }
async-fs = "2" # for async file operation
async-io = "2" # for async timer
blocking = "1" # convert blocking io to async

serde = { version = "1", features = ["derive"], optional = true }

# for http content-disposition parsing
http = { version = "1", optional = true }
regex = { version = "1", optional = true }
language-tags = { version = "0.3", optional = true }
percent-encoding = { version = "2.3", optional = true }
# for http headers
headers = { version = "0.4", optional = true }

# runtime group
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "tracing",
], optional = true }
smol = { version = "2", optional = true }
compio = { version = "0.18", optional = true, default-features = false, features = [
    "io-uring",
    "runtime",
    "io",
    "fs",
] }

# tracing
tracing = { version = "0.1", optional = true }

# terminal progress
indicatif = { version = "0.18", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_System_Memory",
], optional = true }


[dev-dependencies]
bolt-load-tests = { path = "../bolt-load-tests" }

pretty_assertions = { workspace = true }
n0-tracing-test = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-util = { workspace = true, features = ["full"] }

# for stream test
async-stream = "0.3"

# Tracing and bench
tracing-tracy = "0.11"
console-subscriber = "0.5.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = { version = "0.32", features = ["metrics"] }
opentelemetry = { version = "0.31", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.31", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.31", features = ["metrics", "grpc-tonic"] }
opentelemetry-semantic-conventions = { version = "0.31", features = [
    "semconv_experimental",
] }
opentelemetry-stdout = { version = "0.32", features = ["trace", "metrics"] }

# for benchmarks
criterion = { version = "0.8", features = ["async_tokio"] }

[[bench]]
name = "file_writer"
harness = false
